
name: Health Check Pipeline

on:
  schedule:
    - cron:  '30 5,17 * * *'
jobs:
    health-check:
      runs-on: ubuntu-22.04
      steps:
        - name: Check the deployed service URL
          uses: jtalk/url-health-check-action@v3
          with:
            url: https://fso-pokemon.onrender.com|http://fso-pokemon.onrender.com
            max-attempts: 3 # Optional, defaults to 1
            retry-delay: 5s # Optional, only applicable to max-attempts > 1
