name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: windows-2019
    steps:
      - name: Say hello
        run: echo "Hello World!"
      - name: Print Date
        run: date -d
      - name: Print Directory Contents
        run: ls -l
