name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: windows-2019
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"