name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
    simple_deployment_pipeline:
      runs-on: windows-2019
      steps:
        - uses: actions/checkout@v3
  
        - uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: Install Dependencies
          run: npm install
        - name: Check style
          run: npm run eslint
        - run: npm run build
        - run: npm run test
        - name: e2e tests
          uses: cypress-io/github-action@v5
          with:
            command: npm run test:e2e
            start: npm run start-prod
            wait-on: http://localhost:5000
        - name: Render Deploy Action
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
            api-key: ${{ secrets.MY_RENDER_API_KEY }}
            wait-for-success: true