name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
    simple_deployment_pipeline:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: Install Dependencies
          run: npm install
        - name: Check style
          run: npm run eslint
        - run: npm run build
        - run: npm run test
        - name: e2e tests
          uses: cypress-io/github-action@v5
          with:
            command: npm run test:e2e
            start: npm run start-prod
            wait-on: http://localhost:5000
        - name: Trigger deployment
          if: ${{ github.event_name == 'push' }}
          run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
    bump_version:
      runs-on: ubuntu-22.04
      needs: [simple_deployment_pipeline]
      steps:
        - name: Bump version and push tag
          if: ${{ github.event_name == 'push' }}
          uses: anothrNick/github-tag-action@1.64.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch 
            DEFAULT_BRANCH: main
            WITH_V: true
            PRERELEASE: true
            SOURCE: ..\..\
